import Head from "next/head";
import Navbar from "@/components/Navbar";
import Subscriptions from "@/components/Subscriptions";
import Search from "@/components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Echo Verse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar></Navbar>
        <Search></Search>
        <Subscriptions></Subscriptions>
      </div>

    </>
  );
}
